# Generated by Django 3.2.7 on 2021-10-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='desc',
        ),
        migrations.AddField(
            model_name='blog',
            name='title_tag',
            field=models.CharField(default=200, max_length=225),
            preserve_default=False,
        ),
    ]
