# Generated by Django 3.2.7 on 2021-10-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20211008_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default=25, max_length=50),
            preserve_default=False,
        ),
    ]
