# Generated by Django 3.2.7 on 2021-10-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_blog_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_id',
            field=models.CharField(default=23, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
