# Generated by Django 3.2.7 on 2021-10-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
