# Generated by Django 3.2.7 on 2021-10-12 15:08

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0017_remove_blog_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_tag', models.CharField(max_length=225)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('img', models.ImageField(upload_to='images')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='blog',
        ),
    ]
