# Generated by Django 3.2.7 on 2021-10-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0020_bb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bb',
        ),
    ]
