# Generated by Django 3.2.7 on 2021-10-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0029_auto_20211012_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author_use',
        ),
    ]
